import datetime
"""
========================================================================
File: generate_compile_time.py

Description:
    This script generates a compile-time timestamp and writes it to a 
    header file (`compile_time.h`). The timestamp is formatted in 
    12-hour time with an AM/PM indicator.

Usage in PlatformIO:
    - This script is executed as a pre-build step in PlatformIO.
    - It is referenced in the `platformio.ini` file under `extra_scripts`:
        ```
        extra_scripts = pre:generate_compile_time.py
        ```
    - This ensures that every build updates the compile timestamp.

Generated Output:
    - The script writes a `#define` statement to `src/compile_time.h`:
        ```
        #define SC_COMPILE_TIME "MM-DD-YYYY HH:MM:SS AM/PM"
        ```
    - Example output:
        ```
        #define SC_COMPILE_TIME "03-02-2025 12:15:00 AM"
        ```

How to Use in Code:
    - Include the generated `compile_time.h` in your source files:
        ```c
        #include "compile_time.h"
        ```
    - Print or log the compile time:
        ```c
        Serial.println(SC_COMPILE_TIME);
        ```

Notes:
    - The timestamp is dynamically updated at each build.
    - The script must be located in the root project directory for 
      PlatformIO to execute it correctly.
========================================================================
"""

# Generate the current timestamp
compile_time = datetime.datetime.now().strftime("%m-%d-%Y %I:%M:%S %p")

# Write it to a header file with a warning comment
with open("src/compile_time.h", "w") as f:
    f.write("""/*
 * DO NOT EDIT THIS FILE MANUALLY.
 * This file is automatically generated by generate_compile_time.py
 * and will be overwritten during each build.
 *
 * SPDX-FileCopyrightText: 2025 ThingPulse Ltd., https://thingpulse.com
 * SPDX-License-Identifier: MIT
 */

""")
    f.write(f'#define SC_COMPILE_TIME "{compile_time}"\n')