; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:thingpulse-color-kit-grande]
platform = espressif32@~6.10.0
; esp-wrover-kit is 4MB ESP32-WROVER-B compatible.  	
board = esp-wrover-kit
; custom_esp-wrover-kit to enable 8MB flash and 60 album art cache
;board = custom_esp-wrover-kit
framework = arduino
monitor_speed = 115200
upload_speed = 1500000
monitor_filters = 
	esp32_exception_decoder
	time
build_unflags = -std=gnu++11        ; Enable C++ 14 added 1/25/2025
build_flags = 
    -std=gnu++14                    ; Enable C++ 14 to pick up std::make_unique added 1/25/2025
	-DCORE_DEBUG_LEVEL=3            ; was 5 1/2/2025
	-DBOARD_HAS_PSRAM
	-mfix-esp32-psram-cache-issue
	-D USER_SETUP_LOADED=1
	-D ILI9488_DRIVER=1
	-D TFT_MISO=19
	-D TFT_MOSI=18
	-D TFT_SCLK=05
	-D TFT_CS=15
	-D TFT_DC=2
	-D TFT_RST=4
	-D TFT_BL=32
	-D LOAD_GLCD=0
	-D LOAD_FONT2=0
	-D LOAD_FONT4=0
	-D LOAD_FONT6=0
	-D LOAD_FONT7=0
	-D LOAD_FONT8=0
	-D LOAD_GFXFF=0
	-D SMOOTH_FONT=1
	-D SPI_FREQUENCY=27000000
	-I /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/**
extra_scripts = pre:generate_compile_time.py
; no_ota.csv is 4MB ESP32-WROVER-B compatible. limits art cache to 10 albums.  	
board_build.partitions = no_ota.csv
; custom_no_ota.csv is 8MB Flash ESP32-WROVER-E compatible. art cache supports 60 albums.
; board_build.partitions = partitions/custom_no_ota.csv
board_build.filesystem = littlefs
lib_deps = 
	arkhipenko/TaskScheduler @ ^3.8.5
	bodmer/TFT_eSPI @ ^2.5.43
	bodmer/TJpg_Decoder @ ^1.1.0
	bblanchon/ArduinoJson @ ^7.2.1
	https://github.com/Bodmer/OpenFontRender#5e0ec22eef4bc93f963360438a9eb8e5407ef1c4
	https://github.com/witnessmenow/spotify-api-arduino#62612780f40521e9833353eeefcaa0c5d16a97a5
